timeout: 0
verbose: yes
serial: yes
serial_baudrate: 115200
graphics: no
default_entry: 1
interface_branding: LumenOS

/LumenOS
    protocol: limine
    kernel_path: boot():/boot/kernel.elf
    textmode: yes
